---
- hosts: all
  remote_user: vagrant
  become: yes

  vars:
    java_version: 8
    java_subversion:  77
    jenkins_hostname: jenkins.se.cepheid.pri
  roles:
    - basic-config
    - williamyeh.oracle-java
    #- geerlingguy.jenkins - Not worth it.
    - install-jenkins
    - jenkins-plugins
