# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "bento/centos-7.1"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "3072", "--ioapic", "on", "--cpus", "2"]
  end

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # Second network interface for bridged mode
  # enp1s0f0 is one of the interfaces onthe Cisco server which has the public IP 
  config.vm.network "public_network", bridge: "enp1s0f0", ip: "10.70.2.197"

  # delete default gw
  config.vm.provision "shell",
    run: "always",
    inline: "eval `sudo route -n | awk '{ if ($8 ==\"enp0s8\" && $2 != \"0.0.0.0\") print \"sudo route del default gw \" $2; }'`"

  
  config.vm.provision "shell",
    run: "always",
    inline: "eval `sudo route -n | awk '{ if ($8 ==\"enp0s3\" && $2 != \"0.0.0.0\") print \"sudo route del default gw \" $2; }'`"

  # default router
  config.vm.provision "shell",
    run: "always",
    inline: "sudo route add default gw 10.70.2.4"

  config.vm.define "agent1" do |c|
    c.vm.hostname = "jenkins-agent1.se.cepheid.pri"
  end

  config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "provisioning/provision.yml"
        ansible.galaxy_role_file = 'provisioning/requirements.yml'
  end
end

